version: '3.8'
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    depends_on:
      - zookeeper
  kafka-bootstrap:
    container_name: kafka-bootstrap 
    build:
      context: ./bootstrap
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - zookeeper
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=words
  go-producer:
    container_name: go-producer
    build:
      context: ./producer
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - zookeeper
      - kafka-bootstrap
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=words
  go-consumer:
    container_name: go-consumer
    build:
      context: ./consumer
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - zookeeper
      - go-producer
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=words
      - KAFKA_GROUP_ID=go-consumer-1